apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: amozgov/client:e255c1044d162da3d38d6efae24edb4c5373119a
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80  # Исправлен отступ
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      #     livenessProbe:
      #       httpGet:
      #         path: /healthz
      #         port: 80
      #       initialDelaySeconds: 15
      #       periodSeconds: 20
      #     readinessProbe:
      #       httpGet:
      #         path: /ready
      #         port: 80
      #       initialDelaySeconds: 5
      #       periodSeconds: 10
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000