apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: amozgov/converter-service:635574507564e94a0bb82b7d893065034ff1bc01
          ports:
            - containerPort: 5000 # Add the port if your app listens on one
          envFrom:
            - configMapRef:
                name: converter-configmap
            - secretRef:
                name: converter-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
