apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: converter-service
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    path: converter-service/manifest/
    repoURL: https://github.com/IT-life1/microservices.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true