apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: amozgov/notification-service:23cc9d812c44c1e04d2e5e4f0e8d46af0bad97e5
          ports:
            - containerPort: 5000 # Add the port if your app listens on one
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 5000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
