apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  MAIL_RU_ADDRESS: "sanya.mozgov@inbox.ru" #enter your email to get the id
  MAIL_RU_PASSWORD: "Hir8FpggLqUf1XQBd8E4"
type: Opaque
