name: Auth Service CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - 'auth-service/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Укажите версию Python, которую вы используете

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r auth-service/requirements.txt  # Убедитесь, что у вас есть requirements.txt в auth-service

      # Step 4: Run tests
      - name: Run tests
        run: |
          cd auth-service
          python -m unittest discover -s tests  # Запускает все тесты в папке tests

  build-push:
    needs: run-tests  # Эта задача выполняется только если тесты успешны
    uses: ./.github/workflows/docker-build-push.yaml
    with:
      service: auth-service
      branch: ${{ github.head_ref }}

  update-manifests:
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # Step 2: Update deployment manifest
      - name: Update deployment manifest
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}"
          DEPLOYMENT_FILE="./auth-service/manifest/deployment.yaml"
          if [ -f "$DEPLOYMENT_FILE" ]; then
            echo "Updating $DEPLOYMENT_FILE with image: $IMAGE_NAME"
            sed -i "s|image: .*|image: $IMAGE_NAME|" "$DEPLOYMENT_FILE" || { echo "Failed to update manifest"; exit 1; }
          else
            echo "Deployment file not found: $DEPLOYMENT_FILE"
            exit 1
          fi

      # Step 3: Commit updated manifests
      - name: Commit updated manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add ./auth-service/manifest/deployment.yaml
          git diff --quiet || git commit -m "Update auth-service deployment manifest with new image tag"

          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.head_ref }}