name: Build, Push, and Update Kubernetes Manifests

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 3: Build, push, and update manifests for each service
      - name: Process services
        run: |
          # Loop through each service folder
          for service in auth-service gateway-service converter-service notification-service; do
            echo "Processing $service..."

            # Skip if the service directory doesn't exist
            if [ ! -d "$GITHUB_WORKSPACE/$service" ]; then
              echo "Service directory not found: $service"
              continue
            fi

            # Build the Docker image with the GitHub SHA as the tag
            IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/$service:${{ github.sha }}"
            docker build $GITHUB_WORKSPACE/$service -t $IMAGE_NAME

            # Push the image to Docker Hub
            docker push $IMAGE_NAME

            # Update the deployment.yaml file with the new image name
            DEPLOYMENT_FILE="$GITHUB_WORKSPACE/$service/manifest/deployment.yaml"
            if [ -f "$DEPLOYMENT_FILE" ]; then
              echo "Updating $DEPLOYMENT_FILE with image: $IMAGE_NAME"
              sed -i "s|image: .*|image: $IMAGE_NAME|" "$DEPLOYMENT_FILE"
            else
              echo "Deployment file not found: $DEPLOYMENT_FILE"
            fi
          done

      - name: Debug File Paths
        run: |
          for service in auth-service gateway-service converter-service notification-service; do
            DEPLOYMENT_FILE="$GITHUB_WORKSPACE/$service/manifest/deployment.yaml"
            if [ -f "$DEPLOYMENT_FILE" ]; then
              echo "File found: $DEPLOYMENT_FILE"
            else
              echo "File not found: $DEPLOYMENT_FILE"
            fi
          done

      - name: Update deployment.yaml
        run: |
          for service in auth-service gateway-service converter-service notification-service; do
            DEPLOYMENT_FILE="$GITHUB_WORKSPACE/$service/manifest/deployment.yaml"
            if [ -f "$DEPLOYMENT_FILE" ]; then
              echo "Before update:"
              cat "$DEPLOYMENT_FILE"
      
              IMAGE_NAME="${{ secrets.DOCKER_HUB_USERNAME }}/$service:${{ github.sha }}"
              sed -i "s|image: .*|image: $IMAGE_NAME|" "$DEPLOYMENT_FILE"
      
              echo "After update:"
              cat "$DEPLOYMENT_FILE"
            else
              echo "Deployment file not found: $DEPLOYMENT_FILE"
            fi
          done

      # Step 4: Commit updated manifests
      - name: Commit updated manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Stage only modified files
          git add -u

          # Commit changes if there are any
          git commit -m "Update deployment manifests with new image tags"
          git push https://${{ github.USERNAME }}:${{ secrets.TOKEN }}@github.com/IT-life1/microserices.git main
