name: Kind Cluster and ArgoCD Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  setup-kind-cluster:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Verify Docker
      - name: Verify Docker
        run: |
          docker --version
          sudo systemctl start docker
          sudo chmod 666 /var/run/docker.sock

      # Step 3: Verify kubectl
      - name: Verify kubectl
        run: |
          kubectl version --client

      # Step 4: Install Kind
      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      # Step 5: Create a multi-node Kind cluster
      - name: Create Kind cluster with 3 nodes
        run: |
          cat <<EOF | kind create cluster --name my-cluster --config=-
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
            - role: worker
            - role: worker
          EOF
          kubectl cluster-info

      # Step 6: Install ArgoCD
      - name: Install ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      # Step 7: Wait for ArgoCD to be ready
      - name: Wait for ArgoCD to be ready
        run: |
          kubectl wait --for=condition=Ready pods --all -n argocd --timeout=300s

      # Step 8: Deploy PostgreSQL app via ArgoCD
      - name: Deploy PostgreSQL app via ArgoCD
        run: |
          kubectl apply -f ./argocd/argocd-app.yaml

      # Step 9: Wait for auth-app pod to be ready
      - name: Wait for auth-app pod to be ready
        run: |
          kubectl wait --for=condition=Ready pod -l app=auth-app --timeout=300s

      # Step 10: Verify PostgreSQL connection
      - name: Verify PostgreSQL connection
        run: |
          POD_NAME=$(kubectl get pods -l app=auth-app -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $POD_NAME -- sh -c "psql -h localhost -U alex -d authdb"

      # Step 11: Debug if pods are not found
      - name: Debug if pods are not found
        if: failure()
        run: |
          echo "Listing all pods for debugging:"
          kubectl get pods --all-namespaces
          echo "Describing auth-app deployment:"
          kubectl describe deployment auth-app || echo "No deployment found"
          echo "Cluster events:"
          kubectl get events